### ISSUE TITLE
Interval Modal crashes on save

### ISSUE THREAD

**Issue by JacobHearst** [JacobHearst/IntervalTimer#35]
If you attempt to edit an interval, and then press the "add" button, it crashes due to a null pointer. The issue is on [line 124](https://github.com/JacobHearst/IntervalTimer/blob/master/app/src/main/java/com/example/intervaltimer/IntervalModalFragment.kt#L124) and seems to be related to how arguments are passed in.

**Comment by ryan-moeller21** [comment]
I've created a new pull request to fix this.
